<a href="https://colab.research.google.com/github/Dineshkumar013/Bircoin-Prediction/blob/main/Bitcoin_prediction_using_svm.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np 
import pandas as pd

In [ ]:
#Store the data into the variable df
df = pd.read_csv('Bitcoin_dataset_updated.csv')
df.head(7)

         Date  ...  M2(Not seasonally adjusted)[1e+09 USD]
0  2014-01-02  ...                                 11089.3
1  2014-01-03  ...                                 11089.3
2  2014-01-04  ...                                 11089.3
3  2014-01-05  ...                                 11089.3
4  2014-01-06  ...                                 11089.3
5  2014-01-07  ...                                 11089.3
6  2014-01-08  ...                                 11089.3

[7 rows x 9 columns]

In [ ]:
#Remove the Date column
df.drop(['Date'], 1, inplace=True)

In [ ]:
df=df.drop(['n-transactions','btc search trends','fee [USD]','Gold price[USD]','SP500 close index','Oil WTI price[USD]','M2(Not seasonally adjusted)[1e+09 USD]'],axis=1)

In [ ]:
df.dropna()

      BTC price [USD]
0              749.27
1              781.23
2              807.39
3              828.74
4              904.98
...               ...
2305          7507.08
2306          7549.52
2307          7699.27
2308          7790.66
2309          7765.33

[2310 rows x 1 columns]

In [ ]:
#A variable for predicting 'n' days out into the future
prediction_days = 30 #n = 30 days

#Create another column (the target or dependent variable) shifted 'n' units up
df['Prediction'] = df[['BTC price [USD]']].shift(-prediction_days)

In [ ]:
#Show the first 7 rows of the new data set
df

      BTC price [USD]  Prediction
0              749.27      803.00
1              781.23      817.08
2              807.39      814.34
3              828.74      808.50
4              904.98      802.99
...               ...         ...
2305          7507.08         NaN
2306          7549.52         NaN
2307          7699.27         NaN
2308          7790.66         NaN
2309          7765.33         NaN

[2310 rows x 2 columns]

In [ ]:
#CREATE THE INDEPENDENT DATA SET (X)

# Convert the dataframe to a numpy array and drop the prediction column
X = np.array(df.drop(['Prediction'],1))

#Remove the last 'n' rows where 'n' is the prediction_days
X= X[:len(df)-prediction_days]
#X=pd.Dataframe(X)
print(X)

[[ 749.27]
 [ 781.23]
 [ 807.39]
 ...
 [6369.09]
 [6260.95]
 [5885.41]]

In [ ]:
#CREATE THE DEPENDENT DATA SET (y) 
# Convert the dataframe to a numpy array (All of the values including the NaN's)
y = np.array(df['Prediction'])  
# Get all of the y values except the last 'n' rows 
y = y[:-prediction_days] 
print(y)

[ 803.    817.08  814.34 ... 7699.27 7790.66 7765.33]

In [ ]:
# Split the data into 80% training and 20% testing
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [ ]:
# Set prediction_days_array equal to the last 30 rows of the original data set from the price column
prediction_days_array = np.array(df.drop(['Prediction'],1))[-prediction_days:]
print(prediction_days_array)

[[6405.29]
 [6428.28]
 [6652.87]
 [6809.11]
 [6741.67]
 [6871.69]
 [6777.44]
 [7343.2 ]
 [7205.55]
 [7365.03]
 [7293.69]
 [6873.24]
 [6891.6 ]
 [6915.37]
 [6857.66]
 [6871.95]
 [6623.8 ]
 [7112.27]
 [7034.89]
 [7259.36]
 [7130.04]
 [6840.24]
 [6852.52]
 [7130.99]
 [7477.6 ]
 [7507.08]
 [7549.52]
 [7699.27]
 [7790.66]
 [7765.33]]

In [ ]:
from sklearn.svm import SVR 
# Create and train the Support Vector Machine 
svr_rbf = SVR(kernel='rbf', C=1e3, gamma=0.00001)#Create the model
svr_rbf.fit(x_train, y_train) #Train the model

SVR(C=1000.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma=1e-05,
    kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [ ]:
# Testing Model: Score returns the accuracy of the prediction. 
# The best possible score is 1.0
svr_rbf_confidence = svr_rbf.score(x_test, y_test)
print("svr_rbf accuracy: ", svr_rbf_confidence)

svr_rbf accuracy:  0.8669151347659174

In [ ]:
# Print the predicted value
svm_prediction = svr_rbf.predict(x_test)
print(svm_prediction)

print()

#Print the actual values
print(y_test)

[ 5751.90496265  8588.14659669  4419.82644489  7042.88644136
  8519.68891557  6226.00019007  4134.07204674  8835.26268681
  7997.12216912   874.40660474  8335.52198893   624.17398374
   240.27027518   612.58435799  3943.9583497   8226.55765235
   247.58533362   246.74076178  1440.70485972   648.33929054
  8748.30395239   328.78677212   257.90584151   538.78042465
  6185.03556432  7137.55218861  8343.70296609  8760.15368534
   479.74420036  3938.73081593  8748.82303936   357.7203069
   586.03757945  9896.11741529  7854.29642936  1737.83740423
  8582.25633918   622.1893037   7750.67968626  8896.31175026
  8180.4580882    696.7116205    269.57049609   517.14125897
   903.30605208   590.88183259  8053.01767119   236.9602979
  4051.48388884   569.33514857  3884.64641538   431.10155736
   454.35113752  4052.77945485  7536.56270354  6300.34251643
   444.15438144  1012.28664528   893.38343272   540.71927128
  8046.79351537  8831.55873208   245.13038231   239.71024138
   435.39473873  3910.3295531   8586.34450939  6243.95400066
   465.00777652  7215.20039797   245.10873005   582.7297426
   237.55272152  7961.643909     609.20299976 10236.80957077
   408.00809693  3162.98494743   571.84806445  9028.82466298
  3930.51174396   583.70263718   431.52997444   258.51750368
   608.71034406   480.08881591   268.2413213   8148.71173385
   574.09356288  7739.93358061  8781.98537761  6618.86723884
  7923.93696216  6219.89208962   674.65127815  4051.62881831
   879.39994757   660.29105688  8988.80995371  7478.84997048
   814.51765695   883.67050294  8228.61958282   725.62147312
   565.2797702    248.73540323  2848.03417289   477.02511917
  7223.03616853  1009.54431528  4052.92505022   400.35646189
  4006.24351137  9048.83630599   288.23965606  3975.60135512
  1061.77074306  8213.17916826   634.16879831  4094.41199316
  7134.32628543   610.61342244  8828.23439234   492.19724368
   669.88158994  6184.22100521   438.81168809   766.18672938
  6503.18913459   615.07579477  4052.51688244  6223.29593009
   236.86924204  3866.39100389   621.56089752  8073.51730997
   540.56542261   662.44126338   279.52347953  3866.71414347
  7485.0598144   8470.83951725  4000.1778349   8270.19088626
  4212.32059142  3244.28717551  9001.04828815  1013.20504375
   236.7894538    500.80805186  8213.47607346  1449.94451646
  8222.99459282   243.5260107   7517.07973784  3985.87871292
  9526.76036785  3959.28824255   236.32611103  8089.8855523
   587.75988812  8601.28710291  2742.35891928   236.32514456
  6434.00248983   484.5510122    473.68787785  7563.54389497
  6181.25725376   879.27546485   236.34515838  8185.97658022
  8575.04285944   524.49605503   370.87294539   501.92707578
  6372.87979801  3863.34776245  1239.33677192  1245.77393399
   251.75335862  1000.04432859  8265.21513838  6350.27738462
  8103.44098194  6831.61184564  4403.90471488  8372.17725403
   448.78295621   261.10422777   254.21424205 10185.36694053
  3241.07106505  8625.87720754   348.14921649   459.69458607
   703.31446306  3949.80222134  7520.02286372  4203.57257179
   476.84947513   522.18400152   343.49897615  8426.1378631
   261.45590202   237.11869198  3993.88599102   575.10947629
  8363.71493459  6690.35429178   427.95718458  6961.92479731
  4096.13099789  7888.17078585  4220.31776356   568.10949571
  8253.99718926   577.58832484   453.06126034  8335.77770247
  8761.93280505 10008.58633633  1016.36302696  4180.98670602
  1574.77552731   583.25517807   579.20503265   245.17375715
  1568.01179893  8290.71638247  8021.75618784  2694.56123365
   446.4096815    742.81003561   576.54052782   247.22182181
  1197.58845106  6209.61021038   249.20198437  6181.60493852
  1118.66922448   752.61506139   241.53019123  6207.385056
   472.99179736   425.24295854   502.96358161  9898.41140048
  8066.77840992   461.04947972   466.95444895  1333.18717549
   255.52608877   452.80983427   563.77712113   240.48356005
   565.28648733  3873.3464251   8085.81028725  3937.76671012
   779.48875071  6297.97671462   240.00640022   236.59661533
   623.52834261   250.45638692  2972.52083106  4039.97477236
  7484.79284373   580.83474715   250.45201848  6436.97139053
  3965.34333224  7610.90985585   426.70883504  8974.7510111
  3894.83728314  7795.51285455  3885.08280899  3227.73598978
  7593.07730078  7405.32782219   247.85465424   497.82127794
   283.35458128   632.26684797  7599.12539712   436.65635159
  6782.78546891   268.93352756  8447.38008252  8475.06487905
   480.28232186   831.65742385   569.33514857   442.43128241
  7675.92714512 10161.35119764   349.83466544   406.84306422
   249.85834142   240.70644266  6256.13054766  9051.63423746
   237.37548134  8252.85773716   323.83569994   688.85931142
   245.54435169   465.6551534    338.1755064   6503.77926747
   688.57560354  8925.9663953    435.5578903   3930.49667923
  6233.45754675   501.91786652  6185.29128682  6635.92528426
  7313.33322058  3869.13159322   265.32294857   369.60764297
   473.67667433   595.65160039  1254.3565691   7424.03143465
   956.00277644   431.64041972   614.97853263  9160.34152787
   482.74399423  1030.95418719  4251.52506368   477.11286775
   284.70199547  1157.95106822   264.31931767  3978.8500827
   430.86632131  3271.04604043  8065.34974024   456.36302355
   309.57403911   415.03617361   596.61091674  5221.23698323
  8258.32979286  8564.49185883  8832.23684672  9561.39486537
   636.29376198   253.89155823  4389.21331696   705.78031975
   282.85741608  3863.49720106   457.31205716   237.34944637
  9133.25649319  3903.61054046   239.66355058  7836.44819407
  7721.14937523  2899.10962833  8230.83197049  8231.93717016
  1201.44435636   584.68810222 10280.15649939   617.84250731
  3896.53839121  1965.28364178  4052.10715155   437.58820232
  3211.03357793  7947.48897767   612.88048387   748.56659163
  9546.65926561   698.40195086   785.98820038   480.61500847
  3887.81274684  8304.53252374  1129.13005635  8263.2771078
  4048.37387352   243.2301973   3999.89380007   593.59721417
   436.83219076   441.13365394   248.17829308   239.47979476
   242.59755425  2729.97429982  6264.27425754   372.40818989
   263.94174656   354.61353079   586.09617384  3913.63557686
  7726.45787045  8353.29894613   421.40195287   692.95421398
  9751.61261786  7660.63889931   586.97015438  2977.52344404
  8573.7118711    597.56842803   285.21891729  8035.82053258
  4160.71105734   305.78814525   240.83583009 10248.30800549
   243.22256702   734.22770732   252.23926248   241.0554464
  8437.84804453   661.28871342  6454.23078447  3933.96056653
  3946.95112873   246.4412787   4129.57905312  7836.7263448
  7963.77354384  4197.36716647   868.87249752  8246.82002946
  2707.13785744   247.31943568   594.32779445  3891.06705809
  1330.58097718  9090.93421065   668.49939387   342.54352398
  7432.04933016  6289.44509876   331.77372764   466.58086841
   431.77841049 10269.2189629   6976.54716815  8805.42808621
  7659.18943388   377.45762281  6481.20664403   471.44312082]

[ 4405.01 14246.18  4308.33  6583.45 11150.79  4848.78  3865.22  7251.87
  7457.02   673.28 10831.49   563.35   279.43   583.81  5691.69  6195.2
   310.18   247.08   927.93   592.56 11094.24   375.05   278.62   470.83
  3472.98  7286.35 10578.72  8368.1    403.19  4092.07  7337.42   433.66
   649.75  8909.26  9311.7   1073.09 14652.37   705.03  8003.26  8013.91
  7765.33   766.48   234.     399.95  1011.25   643.93  7797.25   322.12
  5986.44   590.    3670.74   418.58   414.83  4911.24  6568.14  6581.07
   454.26   919.97  1000.74   651.85  9484.55  8930.6    236.5    219.93
   443.84  5510.76 11516.83  6373.08   581.    7549.52   227.24   620.43
   279.32 15422.19   518.82 13796.     384.07  3340.28   577.34  8081.81
  5260.65   467.85   453.     224.76   614.77   665.85   260.33 14214.01
   604.13  7309.59 10186.96  7130.04  8662.98  7640.61   727.31  4075.15
   655.71   572.72  9301.18  6577.74   611.05  1001.2   7817.92   667.5
   563.01   286.79  3250.77   531.97  9646.35   883.59  5189.39   429.26
  5900.59  7895.25   442.54  5036.18  1125.    4830.21   591.5   2509.58
 10879.88   615.49  9904.17   452.05   439.12  4140.6    449.37   791.03
  9631.44   727.09  5053.52  7130.99   239.94  3848.33   574.01 11513.42
   635.99   623.91   276.66  3766.89  5890.08  8520.59  3448.58  9577.99
  4318.58  2541.69 11477.01  1180.14   228.33   334.06  7960.04  1518.75
 10858.12   323.48  8739.03  5769.89  8155.48  5280.19   227.53  8297.89
   630.    7067.74  4331.77   235.87  6384.75   444.1    440.88  7386.72
  6588.93   681.96   236.59 16916.8   9349.41   476.92   311.     360.9
 16408.15  3831.45  1279.5   1008.67   284.48  1054.55 11431.37  6489.77
  8020.38  5684.47  4189.38  6760.83   384.07   239.09   270.04 10319.46
  2558.3   9098.27   365.8    416.39   767.28  3658.41  3231.91  3707.5
   577.95   423.68   434.75 17155.95   235.31   228.99  7213.04   595.01
  8283.76  7248.31   455.97  7715.1   3986.28  7625.93  3531.96   606.79
  8895.72   599.     382.62  9471.64  6260.95 10621.29   688.68  6133.16
  1209.99   476.53   595.46   237.97  1770.8   8527.87  9327.48  3210.2
   452.99   892.6    559.54   404.5   1262.2   6342.39   231.52  6466.29
   912.19   958.12   253.28  6390.42   573.85   435.95   390.18  6827.54
 10082.52   574.85   622.08  1030.2    239.55   388.     602.9    231.16
   498.38  4015.95  6849.3   3875.96   999.65  4256.55   231.     284.31
   714.48   230.25  3650.    5175.81  7504.83   503.8    264.47  6358.25
  5276.31  7791.3    425.69  6719.79  3876.85  9324.5   3886.82  2476.63
  9284.51  6626.44   246.77   363.61   210.71   591.69  7402.69   419.13
  6620.63   450.87  9309.15  8910.85   385.09   763.97   477.73   456.31
  8712.35 11386.26   297.99   419.71   235.     233.49  6247.    9854.79
   220.36  8553.61   234.5    730.02   289.     592.81   369.97  8171.65
   742.05  8212.02   415.17  5269.79  4013.52   361.95  3453.66  8220.91
  6724.04  3944.88   245.78   355.79   526.64   570.76  1330.33  7557.72
   921.99   451.     750.71 10354.3    578.07   985.34  4582.52   765.
   226.97  1287.     236.44  5377.19   449.98  2502.86 16914.73   409.62
   376.03   355.3    674.63  6569.22  9294.67  6611.02  7522.39 11960.82
   735.64   356.33  4394.07   758.99   456.    3621.43   751.96   239.94
  6691.39  3686.29   246.49  8534.17  8212.78  2421.26 12612.54  6768.49
  1233.88   622.23 10529.55   369.    3664.38  1079.99  5636.24   450.78
  4054.6   8193.7    638.99   781.32 10760.56   652.87  1013.42   704.5
  4339.05  8184.66   920.    9979.49  3577.79   242.19  3894.48   508.03
   352.21   437.81   262.1    222.11   275.47  2784.8   3425.69   347.96
   358.     351.82   624.07  4029.11  8658.94  8432.23   427.42   778.49
 11186.12  6249.62   653.25  2220.07  8308.01   635.16   208.13  8307.74
  4146.09   376.98   230.97 10016.96   387.02   896.82   223.52   323.78
  8382.03   737.07  7790.66  3604.79  5277.04   216.23  4605.66  8895.78
  5410.23  7392.51   612.48  6612.12  2512.71   244.49   685.91  3629.47
  1390.86  9807.54   629.33   367.12  7757.47  6239.47   284.49   432.63
   452.64 15039.24  6978.63  6369.09  6486.58   407.    7032.3    569.01]

In [ ]:
# Print the predicted value
svm_prediction = svr_rbf.predict(x_test)
print(svm_prediction)

print()

#Print the actual values
print(y_test)

[ 5751.90496265  8588.14659669  4419.82644489  7042.88644136
  8519.68891557  6226.00019007  4134.07204674  8835.26268681
  7997.12216912   874.40660474  8335.52198893   624.17398374
   240.27027518   612.58435799  3943.9583497   8226.55765235
   247.58533362   246.74076178  1440.70485972   648.33929054
  8748.30395239   328.78677212   257.90584151   538.78042465
  6185.03556432  7137.55218861  8343.70296609  8760.15368534
   479.74420036  3938.73081593  8748.82303936   357.7203069
   586.03757945  9896.11741529  7854.29642936  1737.83740423
  8582.25633918   622.1893037   7750.67968626  8896.31175026
  8180.4580882    696.7116205    269.57049609   517.14125897
   903.30605208   590.88183259  8053.01767119   236.9602979
  4051.48388884   569.33514857  3884.64641538   431.10155736
   454.35113752  4052.77945485  7536.56270354  6300.34251643
   444.15438144  1012.28664528   893.38343272   540.71927128
  8046.79351537  8831.55873208   245.13038231   239.71024138
   435.39473873  3910.3295531   8586.34450939  6243.95400066
   465.00777652  7215.20039797   245.10873005   582.7297426
   237.55272152  7961.643909     609.20299976 10236.80957077
   408.00809693  3162.98494743   571.84806445  9028.82466298
  3930.51174396   583.70263718   431.52997444   258.51750368
   608.71034406   480.08881591   268.2413213   8148.71173385
   574.09356288  7739.93358061  8781.98537761  6618.86723884
  7923.93696216  6219.89208962   674.65127815  4051.62881831
   879.39994757   660.29105688  8988.80995371  7478.84997048
   814.51765695   883.67050294  8228.61958282   725.62147312
   565.2797702    248.73540323  2848.03417289   477.02511917
  7223.03616853  1009.54431528  4052.92505022   400.35646189
  4006.24351137  9048.83630599   288.23965606  3975.60135512
  1061.77074306  8213.17916826   634.16879831  4094.41199316
  7134.32628543   610.61342244  8828.23439234   492.19724368
   669.88158994  6184.22100521   438.81168809   766.18672938
  6503.18913459   615.07579477  4052.51688244  6223.29593009
   236.86924204  3866.39100389   621.56089752  8073.51730997
   540.56542261   662.44126338   279.52347953  3866.71414347
  7485.0598144   8470.83951725  4000.1778349   8270.19088626
  4212.32059142  3244.28717551  9001.04828815  1013.20504375
   236.7894538    500.80805186  8213.47607346  1449.94451646
  8222.99459282   243.5260107   7517.07973784  3985.87871292
  9526.76036785  3959.28824255   236.32611103  8089.8855523
   587.75988812  8601.28710291  2742.35891928   236.32514456
  6434.00248983   484.5510122    473.68787785  7563.54389497
  6181.25725376   879.27546485   236.34515838  8185.97658022
  8575.04285944   524.49605503   370.87294539   501.92707578
  6372.87979801  3863.34776245  1239.33677192  1245.77393399
   251.75335862  1000.04432859  8265.21513838  6350.27738462
  8103.44098194  6831.61184564  4403.90471488  8372.17725403
   448.78295621   261.10422777   254.21424205 10185.36694053
  3241.07106505  8625.87720754   348.14921649   459.69458607
   703.31446306  3949.80222134  7520.02286372  4203.57257179
   476.84947513   522.18400152   343.49897615  8426.1378631
   261.45590202   237.11869198  3993.88599102   575.10947629
  8363.71493459  6690.35429178   427.95718458  6961.92479731
  4096.13099789  7888.17078585  4220.31776356   568.10949571
  8253.99718926   577.58832484   453.06126034  8335.77770247
  8761.93280505 10008.58633633  1016.36302696  4180.98670602
  1574.77552731   583.25517807   579.20503265   245.17375715
  1568.01179893  8290.71638247  8021.75618784  2694.56123365
   446.4096815    742.81003561   576.54052782   247.22182181
  1197.58845106  6209.61021038   249.20198437  6181.60493852
  1118.66922448   752.61506139   241.53019123  6207.385056
   472.99179736   425.24295854   502.96358161  9898.41140048
  8066.77840992   461.04947972   466.95444895  1333.18717549
   255.52608877   452.80983427   563.77712113   240.48356005
   565.28648733  3873.3464251   8085.81028725  3937.76671012
   779.48875071  6297.97671462   240.00640022   236.59661533
   623.52834261   250.45638692  2972.52083106  4039.97477236
  7484.79284373   580.83474715   250.45201848  6436.97139053
  3965.34333224  7610.90985585   426.70883504  8974.7510111
  3894.83728314  7795.51285455  3885.08280899  3227.73598978
  7593.07730078  7405.32782219   247.85465424   497.82127794
   283.35458128   632.26684797  7599.12539712   436.65635159
  6782.78546891   268.93352756  8447.38008252  8475.06487905
   480.28232186   831.65742385   569.33514857   442.43128241
  7675.92714512 10161.35119764   349.83466544   406.84306422
   249.85834142   240.70644266  6256.13054766  9051.63423746
   237.37548134  8252.85773716   323.83569994   688.85931142
   245.54435169   465.6551534    338.1755064   6503.77926747
   688.57560354  8925.9663953    435.5578903   3930.49667923
  6233.45754675   501.91786652  6185.29128682  6635.92528426
  7313.33322058  3869.13159322   265.32294857   369.60764297
   473.67667433   595.65160039  1254.3565691   7424.03143465
   956.00277644   431.64041972   614.97853263  9160.34152787
   482.74399423  1030.95418719  4251.52506368   477.11286775
   284.70199547  1157.95106822   264.31931767  3978.8500827
   430.86632131  3271.04604043  8065.34974024   456.36302355
   309.57403911   415.03617361   596.61091674  5221.23698323
  8258.32979286  8564.49185883  8832.23684672  9561.39486537
   636.29376198   253.89155823  4389.21331696   705.78031975
   282.85741608  3863.49720106   457.31205716   237.34944637
  9133.25649319  3903.61054046   239.66355058  7836.44819407
  7721.14937523  2899.10962833  8230.83197049  8231.93717016
  1201.44435636   584.68810222 10280.15649939   617.84250731
  3896.53839121  1965.28364178  4052.10715155   437.58820232
  3211.03357793  7947.48897767   612.88048387   748.56659163
  9546.65926561   698.40195086   785.98820038   480.61500847
  3887.81274684  8304.53252374  1129.13005635  8263.2771078
  4048.37387352   243.2301973   3999.89380007   593.59721417
   436.83219076   441.13365394   248.17829308   239.47979476
   242.59755425  2729.97429982  6264.27425754   372.40818989
   263.94174656   354.61353079   586.09617384  3913.63557686
  7726.45787045  8353.29894613   421.40195287   692.95421398
  9751.61261786  7660.63889931   586.97015438  2977.52344404
  8573.7118711    597.56842803   285.21891729  8035.82053258
  4160.71105734   305.78814525   240.83583009 10248.30800549
   243.22256702   734.22770732   252.23926248   241.0554464
  8437.84804453   661.28871342  6454.23078447  3933.96056653
  3946.95112873   246.4412787   4129.57905312  7836.7263448
  7963.77354384  4197.36716647   868.87249752  8246.82002946
  2707.13785744   247.31943568   594.32779445  3891.06705809
  1330.58097718  9090.93421065   668.49939387   342.54352398
  7432.04933016  6289.44509876   331.77372764   466.58086841
   431.77841049 10269.2189629   6976.54716815  8805.42808621
  7659.18943388   377.45762281  6481.20664403   471.44312082]

[ 4405.01 14246.18  4308.33  6583.45 11150.79  4848.78  3865.22  7251.87
  7457.02   673.28 10831.49   563.35   279.43   583.81  5691.69  6195.2
   310.18   247.08   927.93   592.56 11094.24   375.05   278.62   470.83
  3472.98  7286.35 10578.72  8368.1    403.19  4092.07  7337.42   433.66
   649.75  8909.26  9311.7   1073.09 14652.37   705.03  8003.26  8013.91
  7765.33   766.48   234.     399.95  1011.25   643.93  7797.25   322.12
  5986.44   590.    3670.74   418.58   414.83  4911.24  6568.14  6581.07
   454.26   919.97  1000.74   651.85  9484.55  8930.6    236.5    219.93
   443.84  5510.76 11516.83  6373.08   581.    7549.52   227.24   620.43
   279.32 15422.19   518.82 13796.     384.07  3340.28   577.34  8081.81
  5260.65   467.85   453.     224.76   614.77   665.85   260.33 14214.01
   604.13  7309.59 10186.96  7130.04  8662.98  7640.61   727.31  4075.15
   655.71   572.72  9301.18  6577.74   611.05  1001.2   7817.92   667.5
   563.01   286.79  3250.77   531.97  9646.35   883.59  5189.39   429.26
  5900.59  7895.25   442.54  5036.18  1125.    4830.21   591.5   2509.58
 10879.88   615.49  9904.17   452.05   439.12  4140.6    449.37   791.03
  9631.44   727.09  5053.52  7130.99   239.94  3848.33   574.01 11513.42
   635.99   623.91   276.66  3766.89  5890.08  8520.59  3448.58  9577.99
  4318.58  2541.69 11477.01  1180.14   228.33   334.06  7960.04  1518.75
 10858.12   323.48  8739.03  5769.89  8155.48  5280.19   227.53  8297.89
   630.    7067.74  4331.77   235.87  6384.75   444.1    440.88  7386.72
  6588.93   681.96   236.59 16916.8   9349.41   476.92   311.     360.9
 16408.15  3831.45  1279.5   1008.67   284.48  1054.55 11431.37  6489.77
  8020.38  5684.47  4189.38  6760.83   384.07   239.09   270.04 10319.46
  2558.3   9098.27   365.8    416.39   767.28  3658.41  3231.91  3707.5
   577.95   423.68   434.75 17155.95   235.31   228.99  7213.04   595.01
  8283.76  7248.31   455.97  7715.1   3986.28  7625.93  3531.96   606.79
  8895.72   599.     382.62  9471.64  6260.95 10621.29   688.68  6133.16
  1209.99   476.53   595.46   237.97  1770.8   8527.87  9327.48  3210.2
   452.99   892.6    559.54   404.5   1262.2   6342.39   231.52  6466.29
   912.19   958.12   253.28  6390.42   573.85   435.95   390.18  6827.54
 10082.52   574.85   622.08  1030.2    239.55   388.     602.9    231.16
   498.38  4015.95  6849.3   3875.96   999.65  4256.55   231.     284.31
   714.48   230.25  3650.    5175.81  7504.83   503.8    264.47  6358.25
  5276.31  7791.3    425.69  6719.79  3876.85  9324.5   3886.82  2476.63
  9284.51  6626.44   246.77   363.61   210.71   591.69  7402.69   419.13
  6620.63   450.87  9309.15  8910.85   385.09   763.97   477.73   456.31
  8712.35 11386.26   297.99   419.71   235.     233.49  6247.    9854.79
   220.36  8553.61   234.5    730.02   289.     592.81   369.97  8171.65
   742.05  8212.02   415.17  5269.79  4013.52   361.95  3453.66  8220.91
  6724.04  3944.88   245.78   355.79   526.64   570.76  1330.33  7557.72
   921.99   451.     750.71 10354.3    578.07   985.34  4582.52   765.
   226.97  1287.     236.44  5377.19   449.98  2502.86 16914.73   409.62
   376.03   355.3    674.63  6569.22  9294.67  6611.02  7522.39 11960.82
   735.64   356.33  4394.07   758.99   456.    3621.43   751.96   239.94
  6691.39  3686.29   246.49  8534.17  8212.78  2421.26 12612.54  6768.49
  1233.88   622.23 10529.55   369.    3664.38  1079.99  5636.24   450.78
  4054.6   8193.7    638.99   781.32 10760.56   652.87  1013.42   704.5
  4339.05  8184.66   920.    9979.49  3577.79   242.19  3894.48   508.03
   352.21   437.81   262.1    222.11   275.47  2784.8   3425.69   347.96
   358.     351.82   624.07  4029.11  8658.94  8432.23   427.42   778.49
 11186.12  6249.62   653.25  2220.07  8308.01   635.16   208.13  8307.74
  4146.09   376.98   230.97 10016.96   387.02   896.82   223.52   323.78
  8382.03   737.07  7790.66  3604.79  5277.04   216.23  4605.66  8895.78
  5410.23  7392.51   612.48  6612.12  2512.71   244.49   685.91  3629.47
  1390.86  9807.54   629.33   367.12  7757.47  6239.47   284.49   432.63
   452.64 15039.24  6978.63  6369.09  6486.58   407.    7032.3    569.01]

In [ ]:
#Print the actual price for the next 'n' days, n=prediction_days=30 
df.tail(prediction_days)

      BTC price [USD]  Prediction
2280          6405.29         NaN
2281          6428.28         NaN
2282          6652.87         NaN
2283          6809.11         NaN
2284          6741.67         NaN
2285          6871.69         NaN
2286          6777.44         NaN
2287          7343.20         NaN
2288          7205.55         NaN
2289          7365.03         NaN
2290          7293.69         NaN
2291          6873.24         NaN
2292          6891.60         NaN
2293          6915.37         NaN
2294          6857.66         NaN
2295          6871.95         NaN
2296          6623.80         NaN
2297          7112.27         NaN
2298          7034.89         NaN
2299          7259.36         NaN
2300          7130.04         NaN
2301          6840.24         NaN
2302          6852.52         NaN
2303          7130.99         NaN
2304          7477.60         NaN
2305          7507.08         NaN
2306          7549.52         NaN
2307          7699.27         NaN
2308          7790.66         NaN
2309          7765.33         NaN